routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\ChangePasswordController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\JenisMitraController;
use App\Http\Controllers\KerjaSamaController;
use App\Http\Controllers\LandingController;
use App\Http\Controllers\ProdiController;
use App\Http\Controllers\SuperAdminController;
use App\Http\Controllers\ViewController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MitraController;
use App\Http\Controllers\TemplateController;
use App\Http\Controllers\StatusKerjasamaController;
use App\Http\Controllers\ProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route untuk guest
Route::middleware('guest')->group(function () {
    Route::get('/', [LandingController::class, 'showLanding']);
    Route::get('/templates/{template}/download', [LandingController::class, 'downloadTemplates'])->name('templates.download');
    Route::get('/form', [LandingController::class, 'showForm']);

    Route::get('/login', [LoginController::class, 'create'])->name('login');
    Route::post('/session/login', [LoginController::class, 'login']);

    Route::get('lupa-password', [PasswordResetLinkController::class, 'create'])->name('lupa-password');
    Route::post('lupa-password', [PasswordResetLinkController::class, 'store']);

    Route::get('reset-password/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
    Route::post('reset-password', [NewPasswordController::class, 'store'])->name('password.store');
});

Route::post('/add-datakerjasama', [KerjaSamaController::class, 'storeAdmin']);

// Route untuk user yang sudah login
Route::middleware('auth')->group(function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');

    // Route untuk super admin
    Route::middleware('role:Super Admin')->group(function () {
        Route::get('/manajemen-pengguna', [UserController::class, 'index'])->name('pengguna.manajemen-pengguna');
        Route::get('/manajemen-pengguna/tambah', [UserController::class, 'create'])->name('pengguna.manajemen-pengguna.tambah');
        Route::post('/manajemen-pengguna', [UserController::class, 'store'])->name('pengguna.manajemen-pengguna.store');
        Route::get('/manajemen-pengguna/{user}/edit', [UserController::class, 'edit'])->name('pengguna.manajemen-pengguna.edit');
        Route::put('/manajemen-pengguna/{user}', [UserController::class, 'update'])->name('pengguna.manajemen-pengguna.update');
        Route::get('/manajemen-pengguna/{user}', [UserController::class, 'show'])->name('pengguna.manajemen-pengguna.show');
        Route::post('/update-status', [UserController::class, 'updateStatus'])->name('update.status');
        Route::get('/export-users', [UserController::class, 'exportUsers']);
    });

    Route::middleware('role:Super Admin,Admin,User')->group(function () {
        // Route untuk data kerjasama
        Route::get('/export-kerjasama', [KerjaSamaController::class, 'export']);
        Route::get('/export-kerjasamaBerakhir', [KerjaSamaController::class, 'exportDataBerakhir'])->name('export-data-berakhir');
        Route::get('/export-kerjasamaAktif', [KerjaSamaController::class, 'exportDataAktif'])->name('export-data-Aktif');
        Route::get('/export-kerjasamaAkanBerakhir', [KerjaSamaController::class, 'exportDataAkanBerakhir'])->name('export-data-Akan-Berakhir');
        Route::get('/download/{file}', [KerjaSamaController::class, 'download'])->name('download-data');
        Route::get('/kerjasama', [AdminController::class, 'showKerjasama']);
        Route::get('/kerjasama-Berakhir', [AdminController::class, 'ShowKerjasamaBerakhir']);
        Route::get('/kerjasama-Aktif', [AdminController::class, 'ShowKerjasamaAktif']);
        Route::get('/kerjasama-AkanBerakhir', [AdminController::class, 'ShowKerjasamaAkanBerakhir']);
        Route::put('/kerjasama/{id}', [KerjaSamaController::class, 'update'])->name('kerjasama-update');
    });

    // Route untuk admin dan super admin
    Route::middleware('role:Super Admin,Admin')->group(function () {
        Route::apiResource('template', TemplateController::class)->except(['show', 'destroy']);
        Route::post('template/toggle-status/{template}', [TemplateController::class, 'toggleStatus'])->name('template.toggle-status');
        Route::get('template/download/{template}', [TemplateController::class, 'downloadTemplate'])->name('template.download');

        // Route untuk jenis mitra direferensi
        Route::apiResource('/jenis-mitra', JenisMitraController::class)->except('show');
        Route::get('/jenis-mitra/export', [JenisMitraController::class, 'export'])->name('jenis-mitra.export');

        // Route untuk status mitra direferensi
        Route::get('/status-mou', [StatusKerjasamaController::class, 'index'])->name('status.index');
        Route::post('/status-mou', [StatusKerjasamaController::class, 'store'])->name('status.store');
        Route::put('/status/{status_kerjasama}', [StatusKerjasamaController::class, 'update'])->name('status.update');
        Route::delete('/status/{status_kerjasama}', [StatusKerjasamaController::class, 'destroy'])->name('status.destroy');
        Route::get('/status-mou/{status-mou}', [StatusKerjasamaController::class, 'show'])->name('status.show');
        Route::get('/export-status', [StatusKerjasamaController::class, 'exportStatus'])->name('status.export');

        // Route untuk program studi di referensi
        Route::get('/program-studi', [ProdiController::class, 'index'])->name('prodi.index');
        Route::get('/program-studi/export', [ProdiController::class, 'exportProdi'])->name('prodi.export');
        Route::post('/program-studi', [ProdiController::class, 'store'])->name('prodi.store');
        Route::delete('/program-studi/{prodi}', [ProdiController::class, 'destroy'])->name('prodi.destroy');
        Route::put('/program-studi/{prodi}', [ProdiController::class, 'update'])->name('prodi.update');


        // Route untuk mitra
        Route::get('/mitra', [MitraController::class, 'index'])->name('mitra.index');
        Route::get('/mitra/{mitra}', [MitraController::class, 'show'])->name('mitra.show');
        Route::post('/mitra', [MitraController::class, 'store'])->name('mitra.store');
        Route::get('/mitra/{mitra}/edit', [MitraController::class, 'edit'])->name('mitra.edit');
        Route::put('/mitra/{mitra}', [MitraController::class, 'update'])->name('mitra.update');
        Route::delete('/mitra/{id}', [MitraController::class, 'destroy'])->name('mitra.destroy');
        Route::get('/export-mitra', [MitraController::class, 'exportMitra'])->name('mitra.export');
    });

    Route::get('/download/{file}', [KerjaSamaController::class, 'download'])->name('download-data');
    Route::post('/kerjsama', [KerjaSamaController::class, "delete"])->name('data.destroy');

    // Rooute ganti kata sandi
    Route::get('/change-password', [ChangePasswordController::class, 'show'])->name('password.show');
    Route::post('/change-password', [ChangePasswordController::class, 'store'])->name('password.store');

    Route::get('/profil', [ProfileController::class, 'show'])->name('profil.show');
    Route::get('/edit-profil', [ProfileController::class, 'edit'])->name('profil.edit');
    Route::put('/profil/update/{user}', [ProfileController::class, 'update'])->name('profil.update');
    Route::put('/profil/update-foto/{user}', [ProfileController::class, 'updateFoto'])->name('profil.update.foto');
    Route::get('/logout', [LoginController::class, 'logout']);
});

Route::get('/hello', [ViewController::class, 'showHello']);

resources/views/referensi/admin-jenis-mitra.blade.php
@extends('base')
@section('title', 'SIMKERMA | Jenis Mitra')
@section('konten')
    <div class="page-title-box">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h6 class="page-title">Data Jenis Mitra</h6>
                {{-- Breadcrumb --}}
            </div>
            <div class="col-md-4">
                <div class="d-flex flex-column flex-md-row justify-content-end align-items-md-center gap-3">
                    <a href="{{ route('jenis-mitra.export') }}" class="btn btn-primary waves-effect waves-light"><i
                            class="mdi mdi-content-save"></i> Ekspor</a>
                    <button type="button" class="btn btn-primary waves-effect waves-light" data-bs-toggle="modal"
                            data-bs-target="#modalTambahJenisMitra"><i class="mdi mdi-plus"></i>
                        Tambah Jenis Mitra Baru
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="datatable" class="table table-bordered dt-responsive nowrap"
                               style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                            <thead>
                            <tr>
                                <th>Jenis Mitra</th>
                                <th>Jumlah Mitra</th>
                                <th>Jumlah Kerja Sama</th>
                                <th>Edit</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($jenisMitra as $item)
                                <tr>
                                    <td>{{ $item['nama'] }}</td>
                                    <td>{{ $item['jumlahMitra'] }}</td>
                                    <td>{{ $item['jumlahKerjasama'] }}</td>
                                    <td>
                                        <div class="row gap">
                                            <div class="col">
                                                {{-- Edit Button --}}
                                                <button type="button" class="btn btn-warning waves-effect"
                                                        data-bs-toggle="modal"
                                                        data-bs-target="#modalEditJenisMitra{{ $item['id'] }}"><i
                                                        class="mdi mdi-pencil" style="color: black"></i></button>
                                                {{-- Delete Button --}}
                                                <form action="{{ route('jenis-mitra.destroy', $item['id']) }}"
                                                      method="POST" class="d-inline delete-jenis-mitra">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger waves-effect deleteBtn">
                                                        <i
                                                            class="mdi mdi-trash-can" style="color: black"></i></button>
                                                </form>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        {{-- MODAL TAMBAH JENIS MITRA --}}
        <div id="modalTambahJenisMitra" class="modal fade bs-example-modal-center" tabindex="-1" role="dialog"
             aria-labelledby="mySmallModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <form action="{{ route('jenis-mitra.store') }}" method="POST">
                        @csrf
                        <div class="modal-header">
                            <h5 class="modal-title" id="myModalLabel2">Tambah Jenis Mitra Baru</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="col">
                                <div class="col-md-12 pb-3">
                                    <label for="nama" class="form-label">Nama Jenis Mitra</label>
                                    <input type="text" class="form-control" id="nama" name="nama" required>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Batal</button>
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </form>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
        {{-- MODAL EDIT JENIS MITRA --}}
        @foreach ($jenisMitra as $item)
            <div id="modalEditJenisMitra{{ $item['id'] }}" class="modal fade bs-example-modal-center" tabindex="-1"
                 role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <form action="{{ route('jenis-mitra.update', $item['id']) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="modal-header">
                                <h5 class="modal-title" id="myModalLabel2">Edit Jenis Mitra</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div class="col">
                                    <div class="col-md-12 pb-3">
                                        <label for="nama" class="form-label">Nama Jenis Mitra</label>
                                        <input type="text" class="form-control" id="nama" value="{{ $item['nama'] }}"
                                               name="nama" required>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Batal</button>
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
        @endforeach


        @endsection

        @push('script')
            <script>
                const allJenisMitra = document.querySelectorAll('.delete-jenis-mitra');
                allJenisMitra.forEach(function (jenisMitra) {
                    jenisMitra.addEventListener('submit', function (e) {
                        e.preventDefault();
                        Swal.fire({
                            title: 'Apakah Anda yakin?',
                            text: "Anda tidak akan dapat mengembalikan ini!",
                            icon: 'warning',
                            showCancelButton: true,
                            confirmButtonColor: '#d33',
                            cancelButtonColor: '#3085d6',
                            confirmButtonText: 'Ya, Hapus Data!',
                            cancelButtonText: 'Batal'
                        }).then((result) => {
                            if (result.isConfirmed) {
                                jenisMitra.submit();
                            }
                        });
                    })
                });
            </script>
    @endpush

resources/views/referensi/admin-status-mou.blade.php
@extends('base')
@section('title', 'SIMKERMA | Status MOU')
@section('konten')
    <div class="page-title-box">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h6 class="page-title">Data Status MOU</h6>
                {{-- Breadcrumb --}}
            </div>
            <div class="col-md-4">
                <div class="d-flex flex-column flex-md-row justify-content-end align-items-md-center gap-3">
                    <button class="btn btn-primary" type="button" aria-expanded="false"
                            onclick="window.location.href='/export-status'">
                        <i class="mdi mdi-file-export me-2"></i> Ekspor
                    </button>
                    <button type="button" class="btn btn-primary waves-effect waves-light" data-bs-toggle="modal"
                            data-bs-target="#modalTambahStatusMou"><i class="mdi mdi-plus"></i>
                        Tambah Status MoU Baru
                    </button>
                </div>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card">
        <div class="card-body">
            <div class="row">
                <table id="datatable" class="table table-bordered dt-responsive nowrap"
                       style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Status MoU</th>
                        <th>Edit</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($status as $item)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $item->nama }}</td>
                            <td>
                                <div class="row gap">
                                    <div class="col">
                                        {{-- Edit Button --}}
                                        <button type="button" class="btn btn-warning waves-effect"
                                                data-bs-toggle="modal"
                                                data-bs-target="#edit-modal{{ $item->id }}"><i class="mdi mdi-pencil"
                                                                                        style="color: black"></i>
                                        </button>
                                        {{-- Delete Button --}}
                                        <form action="{{ route('status.destroy', $item->id) }}" method="POST" class="d-inline delete-status">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger waves-effect deleteBtn"><i
                                                    class="mdi mdi-trash-can" style="color: black"></i></button>
                                        </form>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{-- Chart --}}
            </div>
        </div>
    </div>
    {{-- MODAL TAMBAH STATUS MOU --}}
    <div id="modalTambahStatusMou" class="modal fade bs-example-modal-center" tabindex="-1" role="dialog"
         aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <form action="{{ route('status.store') }}" method="POST">
                    @csrf
                    <div class="modal-header">
                        <h5 class="modal-title" id="myModalLabel2">Tambah Status MOU Baru</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="col">
                            <div class="col-md-12 pb-3">
                                <label for="nama" class="form-label">Nama Status</label>
                                <input required type="text" class="form-control" id="nama" name="nama" required>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Batal</button>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->

    @foreach($status as $item)
    {{-- MODAL EDIT STATUS MOU --}}
    <div id="edit-modal{{ $item->id }}" class="modal fade bs-example-modal-center" tabindex="-1" role="dialog"
         aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <form action="{{ route('status.update', $item->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="modal-header">
                        <h5 class="modal-title" id="myModalLabel2">Edit Jenis MOU</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="col">
                            <div class="col-md-12 pb-3">
                                <label for="nama" class="form-label">Nama Jenis Mitra</label>
                                <input type="text" value="{{ $item->nama }}" class="form-control" id="nama" value="" name="nama"
                                       required>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    @endforeach
@endsection

@push('script')
    <script>
        const allStatus = document.querySelectorAll('.delete-status');
        allStatus.forEach(function (status) {
            status.addEventListener('submit', function (e) {
                e.preventDefault();
                Swal.fire({
                    title: 'Apakah Anda yakin?',
                    text: "Anda tidak akan dapat mengembalikan ini!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: 'Ya, Hapus Data!',
                    cancelButtonText: 'Batal'
                }).then((result) => {
                    if (result.isConfirmed) {
                        status.submit();
                    }
                });
            })
        });
    </script>
@endpush